GET http://localhost:3000/produtos HTTP/1.1

###

GET http://localhost:3000/produtos/12 HTTP/1.1

###

POST http://localhost:3000/produtos HTTP/1.1
Content-Type: application/json

{
    "name": "Paracetabem",
    "description": "Usado para curar",
    "price": 150,
    "inventory": 16,
    "category": "Medicamentos",
    "brand": "Cimed"
}

###

DELETE http://localhost:3000/produtos/622f602d8509f6935c0a5973 HTTP/1.1

###

PATCH http://localhost:3000/produtos/622f602d8509f6935c0a5973 HTTP/1.1
Content-Type: application/json

{
    "name": "Paracetamol"
}

###

POST http://localhost:3000/categorias HTTP/1.1
Content-Type: application/json

{
    "name": "Medicamentos",
    "description": "Remédios"
}